server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/mini_mall_user?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD:zyC191380!!}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
      config:
        import-check:
          enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.minimall.user.model
  configuration:
    map-underscore-to-camel-case: true

# JWT 密钥（Day 3 会用到）
jwt:
  secret: ${JWT_SECRET:mini-mall-jwt-secret-key-must-be-at-least-32-bytes-long}
  expiration: ${JWT_EXPIRATION:86400000}  # 24 小时（毫秒）
