server:
  port: 8083

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3307}/mini_mall_product?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD:zyC191380!!}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
      config:
        import-check:
          enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.minimall.product.model
  configuration:
    map-underscore-to-camel-case: true
