apiVersion: v1
kind: ConfigMap
metadata:
  name: mini-mall-config
data:
  NACOS_ADDR: "{{ .Values.config.hostIp }}:{{ .Values.config.nacosPort }}"
  REDIS_HOST: "{{ .Values.config.hostIp }}"
  RABBITMQ_HOST: "{{ .Values.config.hostIp }}"
  DB_HOST: "{{ .Values.config.hostIp }}"
